services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  airflow-init:
    image: apache/airflow:2.7.2
    entrypoint: >
      /bin/bash -c "
        airflow db init &&
        airflow db upgrade &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
    depends_on:
      - postgres
      - redis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins 

  airflow-webserver:
    build:
      context: .
      dockerfile: ../build/Dockerfile
    container_name: airflow-webserver  
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
      ORACLE_HOME: /opt/oracle/instantclient
      LD_LIBRARY_PATH: /opt/oracle/instantclient
      TNS_ADMIN: opt/oracle/instantclient
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: ../build/Dockerfile
    container_name: airflow-scheduler
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
      ORACLE_HOME: /opt/oracle/instantclient
      LD_LIBRARY_PATH: /opt/oracle/instantclient
      TNS_ADMIN: opt/oracle/instantclient
    depends_on:
      - postgres
      - redis
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  airflow-worker:
    build:
      context: .
      dockerfile: ../build/Dockerfile
    container_name: airflow-worker
    image: apache/airflow:2.7.2
    
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
      ORACLE_HOME: /opt/oracle/instantclient
      LD_LIBRARY_PATH: /opt/oracle/instantclient
      TNS_ADMIN: opt/oracle/instantclient
    depends_on:
      - postgres
      - redis
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: celery worker

  airflow-flower:
    build:
      context: .
      dockerfile: ../build/Dockerfile
    container_name: airflow-flower
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
      ORACLE_HOME: /opt/oracle/instantclient
      LD_LIBRARY_PATH: /opt/oracle/instantclient
      TNS_ADMIN: opt/oracle/instantclient
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - redis
      - airflow-init
    command: celery flower

volumes:
  postgres_data:
